Repository ibara1454/secure-shared-preferences, pull requests merged in 2020-05, with the labels that each got.

#1 fix: correct the return value of putXXXs
  secure-shared-preferences/src/main/java/com/github/ibara1454/secure_shared_preferences/shared_preferences/EncryptableSharedPreferences.kt
  secure-shared-preferences/src/test/java/com/github/ibara1454/secure_shared_preferences/shared_preferences/EncryptableSharedPreferencesTest.kt
Labels: bug

#3 fix: replace empty config name
  secure-shared-preferences/src/main/java/com/github/ibara1454/secure_shared_preferences/shared_preferences/SecureSharedPreferencesFactory.kt
  secure-shared-preferences/src/main/java/com/github/ibara1454/secure_shared_preferences/shared_preferences/encrypted/EncryptedSharedPreferencesFactory.kt
Labels: bug

#2 refactor: move tests to sharedTests
  secure-shared-preferences/build.gradle
  secure-shared-preferences/src/sharedTest/java/com/github/ibara1454/secure_shared_preferences/ExtensionUtilsTest.kt
  secure-shared-preferences/src/sharedTest/java/com/github/ibara1454/secure_shared_preferences/cipher/AESDecrypterTest.kt
  secure-shared-preferences/src/sharedTest/java/com/github/ibara1454/secure_shared_preferences/cipher/AESEncrypterTest.kt
  secure-shared-preferences/src/sharedTest/java/com/github/ibara1454/secure_shared_preferences/cipher/Base64DecoderTest.kt
  secure-shared-preferences/src/sharedTest/java/com/github/ibara1454/secure_shared_preferences/cipher/Base64EncoderTest.kt
  secure-shared-preferences/src/sharedTest/java/com/github/ibara1454/secure_shared_preferences/cipher/StringDecrypterTest.kt
  secure-shared-preferences/src/sharedTest/java/com/github/ibara1454/secure_shared_preferences/cipher/StringEncrypter.kt
  secure-shared-preferences/src/sharedTest/java/com/github/ibara1454/secure_shared_preferences/secret/SecretKeysTest.kt
  secure-shared-preferences/src/sharedTest/java/com/github/ibara1454/secure_shared_preferences/shared_preferences/EncryptableSharedPreferencesTest.kt
  secure-shared-preferences/src/sharedTest/java/com/github/ibara1454/secure_shared_preferences/shared_preferences/encrypted/EncryptedSharedPreferencesFactoryTest.kt
Labels: refactoring, test

#5 docs: add a Codacy badge to README.md
  README.md
Labels: documentation

#6 refactor: fix lint errors and add new ktlint task
  .github/workflows/android.yml
  app/src/androidTest/java/com/github/ibara1454/sample/ExampleInstrumentedTest.kt
  app/src/main/java/com/github/ibara1454/sample/MainViewModel.kt
  app/src/test/java/com/github/ibara1454/sample/ExampleUnitTest.kt
  build.gradle
  secure-shared-preferences/src/androidTest/java/com/github/ibara1454/secure_shared_preferences/ExampleInstrumentedTest.kt
  secure-shared-preferences/src/main/java/com/github/ibara1454/secure_shared_preferences/cipher/AESDecrypter.kt
  secure-shared-preferences/src/main/java/com/github/ibara1454/secure_shared_preferences/cipher/AESEncrypter.kt
  secure-shared-preferences/src/main/java/com/github/ibara1454/secure_shared_preferences/cipher/Base64Decoder.kt
  secure-shared-preferences/src/main/java/com/github/ibara1454/secure_shared_preferences/cipher/Base64Encoder.kt
  secure-shared-preferences/src/main/java/com/github/ibara1454/secure_shared_preferences/cipher/FixedIVAESCBCDecrypter.kt
  secure-shared-preferences/src/main/java/com/github/ibara1454/secure_shared_preferences/cipher/FixedIVAESCBCEncrypter.kt
  secure-shared-preferences/src/main/java/com/github/ibara1454/secure_shared_preferences/exception/DecodingException.kt
  secure-shared-preferences/src/main/java/com/github/ibara1454/secure_shared_preferences/exception/DecryptionException.kt
  secure-shared-preferences/src/main/java/com/github/ibara1454/secure_shared_preferences/exception/IllegalBlockSizeException.kt
  secure-shared-preferences/src/main/java/com/github/ibara1454/secure_shared_preferences/exception/InvalidIVException.kt
  secure-shared-preferences/src/main/java/com/github/ibara1454/secure_shared_preferences/exception/InvalidKeyException.kt
  secure-shared-preferences/src/main/java/com/github/ibara1454/secure_shared_preferences/exception/InvalidSpecificationException.kt
  secure-shared-preferences/src/main/java/com/github/ibara1454/secure_shared_preferences/secret/UUIDGenerator.kt
  secure-shared-preferences/src/main/java/com/github/ibara1454/secure_shared_preferences/shared_preferences/EncryptableSharedPreferences.kt
  secure-shared-preferences/src/main/java/com/github/ibara1454/secure_shared_preferences/shared_preferences/SecureSharedPreferencesFactory.kt
  secure-shared-preferences/src/main/java/com/github/ibara1454/secure_shared_preferences/shared_preferences/encrypted/EncryptedSharedPreferencesFactory.kt
  secure-shared-preferences/src/main/java/com/github/ibara1454/secure_shared_preferences/shared_preferences/keystore/KeystoreEncryptedSharedPreferencesFactory.kt
  secure-shared-preferences/src/main/java/com/github/ibara1454/secure_shared_preferences/shared_preferences/safe/SafeSharedPreferences.kt
  secure-shared-preferences/src/main/java/com/github/ibara1454/secure_shared_preferences/shared_preferences/safe/SafeSharedPreferencesFactory.kt
  secure-shared-preferences/src/main/java/com/github/ibara1454/secure_shared_preferences/shared_preferences/safe/SecretKeys.kt
  secure-shared-preferences/src/sharedTest/java/com/github/ibara1454/secure_shared_preferences/cipher/AESDecrypterTest.kt
  secure-shared-preferences/src/sharedTest/java/com/github/ibara1454/secure_shared_preferences/cipher/AESEncrypterTest.kt
  secure-shared-preferences/src/sharedTest/java/com/github/ibara1454/secure_shared_preferences/cipher/StringEncrypterTest.kt
  secure-shared-preferences/src/sharedTest/java/com/github/ibara1454/secure_shared_preferences/secret/SecretKeysTest.kt
  secure-shared-preferences/src/sharedTest/java/com/github/ibara1454/secure_shared_preferences/shared_preferences/EncryptableSharedPreferencesTest.kt
  secure-shared-preferences/src/sharedTest/java/com/github/ibara1454/secure_shared_preferences/shared_preferences/encrypted/EncryptedSharedPreferencesFactoryTest.kt
Labels: chore, refactoring

#7 chore: refactor workflow
  .editorconfig
  .github/workflows/build.yml
  .github/workflows/pull_reqeust.yml
  .github/workflows/release.yml
Labels: chore

#9 fix: add synchronized blocks to critical read/write
  secure-shared-preferences/src/main/java/com/github/ibara1454/secure_shared_preferences/shared_preferences/SecureSharedPreferencesFactory.kt
  secure-shared-preferences/src/main/java/com/github/ibara1454/secure_shared_preferences/shared_preferences/encrypted/EncryptedSharedPreferencesFactory.kt
  secure-shared-preferences/src/main/java/com/github/ibara1454/secure_shared_preferences/shared_preferences/safe/SafeSharedPreferencesFactory.kt
  secure-shared-preferences/src/main/java/com/github/ibara1454/secure_shared_preferences/shared_preferences/safe/SecretKeys.kt
Labels: bug
